name: Python CI

on:
  push:
    branches:
      - main
      - zifan
      - new_main

  pull_request:
    branches:
      - main
      - zifan
      - new_main


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        subdir: ["machine_learning_client","web-app"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check Python version
        run: |
          python --version
          which python
          echo $PATH

      - name: Install dependencies in ${{ matrix.subdir }}
        run: |
          cd ${{ matrix.subdir }}
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev 

      - name: Run Tests
        run: |
          cd ${{ matrix.subdir }}
          pipenv run pytest --maxfail=1 --disable-warnings -q