name: Python Package CI

on:
  push:
    branches:
      - main
      - zifan 
  pull_request:
    branches:
      - main
      - zifan

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
        subdir: [ "machine-learning-client" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies in ${{ matrix.subdir }}
        run: |
          cd ${{ matrix.subdir }}
          python -m pip install --upgrade pip
          # Install pipenv if you're using it for dependency management.
          pip install pipenv
          # This installs all runtime and dev dependencies as specified in your Pipfile.
          pipenv install --system --dev

      - name: Build package in ${{ matrix.subdir }}
        run: |
          cd ${{ matrix.subdir }}
          pip install .

      - name: Run Tests in ${{ matrix.subdir }}
        run: |
          cd ${{ matrix.subdir }}
          pytest --maxfail=1 --disable-warnings -q